version: '3'
services:
  app:
    depends_on:
      - db
    container_name: app
    ports:
      - "3000:8000"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      USER_ID: $${id -u}
      GROUP_ID: $${id -g}
      DB_HOST: db
    env_file:
      - .env.docker
    working_dir: /app
    command: /usr/local/bin/python3 manage.py runserver 0:8000
    links:
        - db
    volumes:
      - type: bind
        source: .
        target: /app
