version: 2.1
jobs:
  build:
    working_directory: ~/project
    machine:
       image: ubuntu-2004:2024.01.2
    steps:
      - checkout
      - run: docker build -t app -f docker/for_ci/app_for_pytest/Dockerfile .
      - run: docker login -u $DOCKER_HUB_USER_NAME -p $DOCKER_HUB_ACCESS_TOKEN
      - run: docker tag app $DOCKER_HUB_USER_NAME/chuniscorerecorder_ci_test_app
      - run: docker push $DOCKER_HUB_USER_NAME/chuniscorerecorder_ci_test_app
  test:
    working_directory: ~/project
    docker:
      - image: $DOCKER_HUB_USER_NAME/chuniscorerecorder_ci_test_app
        environment:
          DB_NAME: chuni_recorder_test
          DB_USER: chuni
          DB_PASS: chuni
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          TEST_DB_NAME: chuni_recorder_test
          DJANGO_DEBUG_MODE: true
          ALLOWED_HOSTS: '*'
          MODE: LOCAL
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: chuni_recorder_test
          MYSQL_USER: chuni
          MYSQL_PASSWORD: chuni
    steps:
      - checkout
      - run: cd /app
      - run: sleep 20
      - run: pytest
workflows:
  version: 2
  build_compose_and_test:
    jobs:
      - build
      - test:
          requires:
            - build