version: 2.1
jobs:
  build:
    working_directory: ~/project
    machine:
       image: cimg/ubuntu-2004
    steps:
      - checkout
      - run: cp .env.docker.example .env.docker
      - run: docker compose -f docker-compose.yml -f docker-compose.dev.yml build
  test:
    working_directory: ~/project
    machine:
       image: cimg/ubuntu-2004
    steps:
      - run: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d
      - run: sleep 10
      - run: docker compose -f docker-compose.yml -f docker-compose.dev.yml exec app pytest

workflows:
  version: 2
  build_compose_and_test:
    jobs:
      - build
      - test