# Generated by Django 4.2.11 on 2024-04-09 14:32

from django.db import migrations, models


def insert_difficulty(apps, schema_editor):
    difficulty_rank = apps.get_model("chuniscore_recorder", "ChuniDifficultyRank")
    difficultys = ["BASIC", "ADVANCED", "EXPERT", "MASTER", "WORLD'S END", "ULTIMA"]
    for difficulty in difficultys:
        difficulty_rank.objects.create(difficulty_rank=difficulty)


class Migration(migrations.Migration):

    dependencies = [
        (
            "chuniscore_recorder",
            "0002_chunidifficulty_chunidifficultyrank_chunigenres_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(insert_difficulty),
    ]
