# Generated by Django 4.2.11 on 2024-04-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chuniscore_recorder", "0003_auto_20240409_1432"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChuniUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_name",
                    models.CharField(help_text="プレイヤー名", max_length=255),
                ),
                ("best_rating", models.IntegerField(help_text="べ枠レーティング")),
                ("update_date", models.DateTimeField(help_text="更新日時")),
            ],
            options={
                "db_table": "chuni_users",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="chuni_user_name",
        ),
        migrations.AddField(
            model_name="user",
            name="chuni_user",
            field=models.OneToOneField(
                blank=True,
                help_text="チュウニズムのプレイヤー名",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_chuni_user",
                to="chuniscore_recorder.chuniuser",
            ),
        ),
        migrations.AlterField(
            model_name="chuniresult",
            name="user",
            field=models.ForeignKey(
                help_text="ユーザー名",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_user",
                to="chuniscore_recorder.chuniuser",
            ),
        ),
    ]
